name: Sync 3x-ui Image

on:
  workflow_dispatch: # 允许你在网页端手动点击按钮触发

jobs:
  sync-image:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync from MHSanaei to My Registry
        run: |

          docker pull ghcr.io/mhsanaei/3x-ui:v2.9.3
          
          docker tag ghcr.io/mhsanaei/3x-ui:v2.9.3 ghcr.io/${{ github.repository_owner }}/panel:v2.9.3
          
          docker push ghcr.io/${{ github.repository_owner }}/panel:v2.9.3
